protected/controllers/ConfiguracionesController.php
<?php
class ConfiguracionesController extends Controller{

	public function filters(){
		return array(array('CrugeAccessControlFilter'));
	}

	public function actionIndex(){
		$model=Configuraciones::model()->findByPk(1);

		if(isset($_POST['Configuraciones'])){
			$model->attributes=$_POST['Configuraciones'];
			if($model->save()){
				Yii::app()->user->setFlash('success', "Configuraciones guardadas con éxito");
			}
		}


		$this->render('index',compact('model'));
	}
	
}

protected/controllers/PrestamosController.php
<?php
class PrestamosController extends Controller{
	
	public $layout='//layouts/column2';


	public function filters(){
		return array(array('CrugeAccessControlFilter'));
	}

	
	public function actionView($id){
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	
	public function actionCreate($idSolicitante=null){
		$model=new Prestamos;
		$model->id_solicitante=!is_null($idSolicitante)?$idSolicitante:'';

		// $this->performAjaxValidation($model);

		if(isset($_POST['Prestamos'])){
			$_POST=$model->ordenarRegistro($_POST);
			$model->attributes=$_POST['Prestamos'];
			if(!$model->validarDisponible()){
				Yii::app()->user->setFlash('error', "El préstamo que está solicitando supera el monto máximo a prestar, Por favor intente con un monto menor");
			}else{
				
				if($model->save()){
					$mensaje=$this->renderPartial("_notificaciones",compact('model'),true);
					$this->enviarCorreo($model->idSolicitante->email,Yii::app()->name,$mensaje);
					$this->redirect(array('view','id'=>$model->id_prestamo));
				}
			}
		}


		if(is_null($idSolicitante)){
			$this->render('createBuscarSolicitante');
		}else{
			$modelSolicitante=Solicitantes::model()->find(array('condition'=>"id_solicitante=$idSolicitante"));
			if(!$modelSolicitante){
				$this->redirect(array('create'));
			}
			$listaCuotas=Configuraciones::model()->listaCuotas();
			$this->render('create',compact('model','modelSolicitante','listaCuotas'));	
		}
		
	}

	
	public function actionUpdate($id){
		$model=$this->loadModel($id);

		// $this->performAjaxValidation($model);

		if(isset($_POST['Prestamos'])){
			$model->attributes=$_POST['Prestamos'];
			if($model->save()){
				$this->redirect(array('view','id'=>$model->id_prestamo));
			}
		}

		$this->render('update',compact('model'));
	}

	
	public function actionDelete($id){
		$this->loadModel($id)->delete();

		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	
	/*public function actionIndex(){
		$dataProvider=new CActiveDataProvider('Prestamos');
		$this->render('index',compact('dataProvider'));
	}*/

	
	public function actionAdmin(){
		$model=new Prestamos('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Prestamos']))
			$model->attributes=$_GET['Prestamos'];

		$listaEstatus=PrestamosEstatus::model()->getListaEstatus();

		$this->render('admin',compact('model','listaEstatus'));
	}


	public function actionAutorizar($id){
		$model=$this->loadModel($id);
		if($model->id_estatus != 1){
			Yii::app()->user->setFlash('error', "El préstamo tiene un estatus que no permite esta acción");
			$this->redirect(array('admin'));
		}

		$dia=date("d");
		//$dia=21;
		if($dia > 20){
			Yii::app()->user->setFlash('error', "Sólo se pueden autorizar préstamos los primeros 20 días de cada mes.");
			$this->redirect(array('admin'));
		}		

		if(isset($_POST['Prestamos'])){
			$_POST=$model->ordenarAutorizacion($_POST);
			$model->attributes=$_POST['Prestamos'];
			if($model->save()){
				$mensaje=$this->renderPartial("_notificaciones",compact('model'),true);
				$this->enviarCorreo($model->idSolicitante->email,Yii::app()->name,$mensaje);
				Yii::app()->user->setFlash('success', "Préstamo autorizado con éxito");
				$this->redirect(array('view','id'=>$model->id_prestamo));
			}
		}

		$this->render('autorizar',compact('model'));
	}


	public function actionRechazar($id){
		$model=$this->loadModel($id);
		if($model->id_estatus != 1){
			Yii::app()->user->setFlash('error', "El préstamo tiene un estatus que no permite esta acción");
			$this->redirect(array('admin'));
		}

		if(isset($_POST['Prestamos'])){
			$_POST=$model->ordenarRechazo($_POST);
			$model->attributes=$_POST['Prestamos'];

			if($model->save()){
				$mensaje=$this->renderPartial("_notificaciones",compact('model'),true);
				$this->enviarCorreo($model->idSolicitante->email,Yii::app()->name,$mensaje);
				Yii::app()->user->setFlash('success', "Préstamo rechazado");
				$this->redirect(array('view','id'=>$model->id_prestamo));
			}
		}

		$this->render('rechazar',compact('model'));
	}


	public function actionEntregar($id){
		$model=$this->loadModel($id);
		if($model->id_estatus != 2){
			Yii::app()->user->setFlash('error', "El préstamo tiene un estatus que no permite esta acción");
			$this->redirect(array('admin'));
		}

		if(isset($_POST['Prestamos'])){
			if($model->fecha_tentativa_entrega > date("Y-m-d")){
				Yii::app()->user->setFlash('error', "Para entregar el préstamo debe esperar la fecha tentativa de entrega del mismo.");
				$this->redirect(array('admin'));
			}
			$_POST=$model->ordenarEntrega($_POST);
			$model->attributes=$_POST['Prestamos'];
			if($model->save()){
				$mensaje=$this->renderPartial("_notificaciones",compact('model'),true);
				$this->enviarCorreo($model->idSolicitante->email,Yii::app()->name,$mensaje);
				Yii::app()->user->setFlash('success', "Préstamo entregado con éxito");
				$this->redirect(array('view','id'=>$model->id_prestamo));
			}
		}

		$this->render('entregar',compact('model'));
	}


	public function actionCuotas($id){
		$model=$this->loadModel($id);
		if($model->id_estatus != 3){
			Yii::app()->user->setFlash('error', "El préstamo tiene un estatus que no permite esta acción");
			$this->redirect(array('admin'));
		}

		$modelCuotas=new PrestamosCuotas;
		$modelCuotas->id_prestamo=$id;
		$modelCuotas->monto=number_format($model->montoCuotas(), 2, '.', '');

		$model->cuotas_canceladas=count($model->prestamosCuotas);
		$model->cuotas_faltantes=$model->getCuotasFaltantes();
		$model->monto_cancelado=$model->getMontoCancelado();
		$model->monto_faltante=$model->getMontoFaltante();

		if(isset($_POST['PrestamosCuotas'])){
			$_POST=$modelCuotas->ordenarPago($_POST);
			$modelCuotas->attributes=$_POST['PrestamosCuotas'];
			if($modelCuotas->save()){
				if($model->validarPagoTotal()){
					$mensaje=$this->renderPartial("_notificacionesCuotaFinal",compact('model','modelCuotas'),true);
				}else{
					$mensaje=$this->renderPartial("_notificacionesCuota",compact('model','modelCuotas'),true);
				}
				$this->enviarCorreo($model->idSolicitante->email,Yii::app()->name,$mensaje);
				Yii::app()->user->setFlash('success', "Pago de cuota registrado con éxito");
				$this->redirect(array('view','id'=>$model->id_prestamo));
			}
		}

		$this->render('cuotas',compact('model','modelCuotas'));
	}

	
	public function loadModel($id){
		$model=Prestamos::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}


	public function actionBuscarSolicitante(){
		$identificacion=$_POST['identificacion'];
		$modelSolicitante=Solicitantes::model()->find(array('condition'=>"identificacion=$identificacion"));
		echo $modelSolicitante?$modelSolicitante->id_solicitante:false;
	}


	public function actionGeneral(){
		$model=new Prestamos;
		$prestadoActual=$model->getPrestadoActual();
		$disponible=$model->getMontoDisponible();
		$modelConfig=Configuraciones::model()->findByPk(1);
		$this->render("general",compact('modelConfig','prestadoActual','disponible'));
	}

	
	protected function performAjaxValidation($model){
		if(isset($_POST['ajax']) && $_POST['ajax']==='prestamos-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}


	public function actionMail(){
		$mensaje = "Línea 1\r\nLínea 2\r\nLínea 3";
		$mensaje = wordwrap($mensaje, 70, "\r\n");
		$this->enviarCorreo("osman2907@gmail.com","Prueba de Envíos",$mensaje);
	}

}

protected/controllers/ReportesController.php
<?php
class ReportesController extends Controller{

	public function filters(){
		return array(array('CrugeAccessControlFilter'));
	}

	public function actionIndex(){
		$modelRep=new Reportes;
		$listaAnios=$modelRep->getListaAnios();
		$listaMeses=$modelRep->getListaMeses();
		if(isset($_POST['anio'])){
			$anioReporte=$_POST['anio'];
			$data=$modelRep->getGraficoCantidades($anioReporte);
			$dataMontos=$modelRep->getGraficoMontos($anioReporte);
		}
		$this->render('index',compact('listaAnios','listaMeses','data','dataMontos','anioReporte'));
	}


	public function actionGeneral(){
		$anio=$_POST['anio'];
		$this->renderPartial("_general",compact('anio'));
	}

}

protected/controllers/SolicitantesController.php
<?php
class SolicitantesController extends Controller{
	
	public $layout='//layouts/column2';

	
	public function filters(){
		return array(array('CrugeAccessControlFilter'));
	}

	
	public function actionView($id){
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	
	public function actionCreate($identificacion = null){
		$model=new Solicitantes;
		$model->identificacion=!is_null($identificacion)?$identificacion:'';

		// $this->performAjaxValidation($model);

		if(isset($_POST['Solicitantes'])){
			$model->attributes=$_POST['Solicitantes'];
			if($model->save()){
				if(!is_null($identificacion)){
					$this->redirect(array('/prestamos/create','idSolicitante'=>$model->id_solicitante));
				}else{
					$this->redirect(array('view','id'=>$model->id_solicitante));
				}
			}
		}

		$this->render('create',compact('model'));
	}

	
	public function actionUpdate($id){
		$model=$this->loadModel($id);

		// $this->performAjaxValidation($model);

		if(isset($_POST['Solicitantes'])){
			$model->attributes=$_POST['Solicitantes'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_solicitante));
		}

		$this->render('update',compact('model'));
	}

	
	public function actionDelete($id){
		$this->loadModel($id)->delete();

		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	
	/*public function actionIndex(){
		$dataProvider=new CActiveDataProvider('Solicitantes');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}*/

	
	public function actionAdmin(){
		$model=new Solicitantes('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Solicitantes']))
			$model->attributes=$_GET['Solicitantes'];

		$this->render('admin',compact('model'));
	}

	
	public function loadModel($id){
		$model=Solicitantes::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	
	protected function performAjaxValidation($model){
		if(isset($_POST['ajax']) && $_POST['ajax']==='solicitantes-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
	<div class="col-md-9">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="col-md-3">
		<div id="sidebar">
		<?php
			$this->beginWidget('zii.widgets.CPortlet', array(
				'title'=>'Operaciones',
			));
			$this->widget('zii.widgets.CMenu', array(
				'items'=>$this->menu,
				'htmlOptions'=>array('class'=>'operations'),
			));
			$this->endWidget();
		?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="language" content="en">

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css">
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css">

	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jquery/jquery-3.1.0.min.js"></script>

	

	<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/librerias.js"></script>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>

	<script type="text/javascript">
		$(document).ready(function(){
			setInterval(function(){ $(".flash-mensaje").remove(); }, 6000);
		});
	</script>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo">
			<img class="logo-cabecera" src="<?php echo Yii::app()->request->baseUrl; ?>/images/logo.png"/>
			<?php echo CHtml::encode(Yii::app()->name); ?>
		</div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Inicio', 'url'=>array('/site/index')),
				array('label'=>'Iniciar Sesión', 'url'=>array('/cruge/ui/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Préstamos', 'url'=>array('/prestamos/admin'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Solicitantes', 'url'=>array('/solicitantes/admin'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Reportes', 'url'=>array('/reportes/index'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Configuraciones', 'url'=>array('/configuraciones/index'), 'visible'=>!Yii::app()->user->isGuest),
				array('label'=>'Gestión de Usuarios', 'url'=>array('/cruge/ui/usermanagementadmin'), 'visible'=>!Yii::app()->user->isGuest),

				//array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				//array('label'=>'Contact', 'url'=>array('/site/contact')),
				//array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Cerrar Sesión ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->
	<?php if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif?>

	<?php
    foreach(Yii::app()->user->getFlashes() as $key => $message){
        echo '<div class="flash-mensaje flash-' . $key . '">' . $message . "</div>\n";
    }
	?>

	<?php echo $content; ?>

	<div class="clear"></div>

	<div id="footer">
		<strong>EVALUCIÓN ILERNUS <?php echo date("Y") ?></strong>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>